### Register a new user
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "name": "Earljoe Kadima",
    "email": "earljoe06@outlook.com",
    "password": "password"
}

###Login 
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "admin@yopmail.com",
    "password": "password"
}

### Activate user
GET http://localhost:3000/api/auth/activate/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjZDUzNGQwNi1jMzc3LTRkNzYtOGE4YS1hMmYxNGM5MGI2MjQiLCJyb2xlIjp0cnVlLCJpYXQiOjE3MTg5Njc4ODMsImV4cCI6MTcxOTA1NDI4M30.uQT_9P0Pw9Zy342pAi4gnC3boESCWelgfAXGMGDWicg
